client:
    image: nginx
    ports:
        - "80:80"
    volumes:
        - client:/usr/share/nginx/html
    links:
        - api

api:
    build: api
    ports:
        - "8080:8080"
    volumes:
        - api:/var/www
    links:
        - rabbitmq

fetcher:
    build: fetcher
    volumes:
        - fetcher:/var/www
    links:
        - rabbitmq

rabbitmq:
    image: rabbitmq:3-management
    ports:
        - "8081:15672"
